parameters:
    legal.owner_name: '%env(LEGAL_OWNER_NAME)%'
    legal.owner_address: '%env(LEGAL_OWNER_ADDRESS)%'
    legal.contact_email: '%env(LEGAL_CONTACT_EMAIL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Security\UserChecker:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
